### ISSUE TITLE
Issue with 'encoding' argument

### ISSUE THREAD

**Issue by evanseitz** [mariusvniekerk/conda-lock#1]
Hi, I'm hitting an error with running this script. I'm on macOS Mojave 64 bit and have created the environment.yml. 

I've `chmod 755` the `conda-lock.py` file and added the interpreter location at the top of the script via `#! /Users/.../bin/python` (using `which python`)

However, I'm running into an issue I can't solve with error message:

```
216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
Is there any advice you can provide? Thank you so much for your time.

**Comment by mariusvniekerk** [comment]
Closed in https://github.com/mariusvniekerk/conda-lock/commit/0f29cc117ac07a8980e598becfff270424ca6240
