### ISSUE TITLE
How does this relate to conda export --explicit?

### ISSUE THREAD

**Issue by dhirschfeld** [mariusvniekerk/conda-lock#19]
Hi Marius,
This seems pretty interesting as we are also trying to explicitly specify a reproducible environment. One of the key aims is to ensure that the environment deployed to prod is exactly the same as was used when running the tests.

Is the lock file generated by `conda-lock` the same as created by `conda list --explicit`?

**Comment by mariusvniekerk** [comment]
It is in fact the same as the lock from `--explicit`.  The main difference is that conda-lock doesn't actually require you to create the environment, just to be able to solve for it.

**Comment by dhirschfeld** [comment]
That does sound very interesting. We've had to jump through a few hoops to get this functionality in our custom CI pipelines so I'm sure it'll be of general use to other who care about exact reproducibility.

To avoid the cost of an extra install to simply create a "lock" file we hook into the test phase of our CI, immediately after the package is installed into the test env, but *before* the test deps are installed. So it's a bit of a hack and much nicer to be able to export the "lock" file without having to jump through such hoops.

**Comment by dhirschfeld** [comment]
It kindof seems like `conda` itself should have this functionality builtin :/

Anyway, closing as asked & answered - thanks!
