### ISSUE TITLE
Error with -p argument?

### ISSUE THREAD

**Issue by evanseitz** [mariusvniekerk/conda-lock#2]
I've made several attempts to create the lock methods using the repository you've so kindly recommended. However, I must be making a mistake somewhere in my logic; I'm doing the following on Linux:

1. placing the `conda_lock.py` file on my local system
2. adding the path to my python interpreter at the top of this script via `#! /Users/.../bin/python` (taken from `which python`)
3. making the script executable via `chmod 755 conda_lock.py`
4. activating the environment that I'm interested in locking via `conda activate FOO` and creating a .yml file for it via `conda env export > environment.yml` (which now resides in the same directory as `conda_lock.py`... then deactivating environment
5. `pip install pathlib` on the conda `base` (the script will fuss if not)
6. in this directory, using `./conda-lock.py -f environment.yml -p osx-64 -p linux-64` as directed in the readme

At this point, I'm getting the error:
```
TypeError: expected str, bytes or os.PathLike object, not dict
ees2192@midway:~/conda-lock-master> ./conda_lock.py -f environment.yml
generating lockfile for osx-64
Traceback (most recent call last):
  File "./conda_lock.py", line 107, in <module>
    platforms=args.platform or DEFAULT_PLATFORMS,
  File "./conda_lock.py", line 64, in make_lock_files
    platform=platform, channels=channels, specs=specs
  File "./conda_lock.py", line 37, in solve_specs_for_arch
    json_output = subprocess.check_output(args, encoding="utf-8", env=env)
  File "/home/ees2192/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ees2192/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ees2192/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ees2192/anaconda3/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not dict
```
I should note that this happens in different flavors when I remove one of the `-p arguments` or all of them from `./conda-lock.py -f environment.yml -p osx-64 -p linux-64`.

**Comment by mariusvniekerk** [comment]
@evanseitz you should not have to install `pathlib` since it is part of the standard library in python3.

Do you have the `environment.yml` around

**Comment by evanseitz** [comment]
I do, and sorry for the trouble:
[environment.txt](https://github.com/mariusvniekerk/conda-lock/files/3637049/environment.txt)

(I've had to change it from .yml to .txt to attach here)

**Comment by mariusvniekerk** [comment]
So the environment that you work from here is platform specific.   That is not how conda-lock works.

What you want instead is something that pins **only** the requirements you have to pin. 

For example:

```
channels:
  - menpo
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python 3.7
  - matplotlib	
  - scikit-learn
  - scikit-image <=0.13
```

If you already have an environment that you have created before you can just generate the same kind of file that conda-lock would using `conda list --explicit`.

**Comment by evanseitz** [comment]
Okay, thank you very much for clarifying. I'll look into your advice.
