### ISSUE TITLE
mamba support

### ISSUE THREAD

**Issue by dhirschfeld** [mariusvniekerk/conda-lock#20]
Using `mamba` can be a *huge* time saver - it would be great if `conda-lock` could optionally use `mamba` for the solve

**Comment by mariusvniekerk** [comment]
does mamba have a dry run mode that we can use?

**Comment by mariusvniekerk** [comment]
Actually it looks like it might already have mamba support if mamba produces the same dry-run output as conda.

Try running
```
conda-lock --conda mamba
```

**Comment by mariusvniekerk** [comment]
we can make that behave a little cleaner, but just tested it and it works

**Comment by ocefpaf** [comment]
Last time I tried that with the pangeo
 mamba defaulted to conda's solver though. But it is nice to know we can just point to its path.

**Comment by dhirschfeld** [comment]
> *just tested it and it works*

That's cool! 🚀 

I know the mamba devs were recently working on JSON support so I hoped there wouldn't be too much else to do.

This will be interesting/useful to compare the solver output...

**Comment by dhirschfeld** [comment]
Happy for this issue to be closed then since it already works!
