### ISSUE TITLE
[Bug] `msys2` channel packages not included w/ `defaults` channel

### ISSUE THREAD

**Issue by alanhdu** [mariusvniekerk/conda-lock#22]
Right now, if I use the following environment YAML:

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - make==4.3
```

Then calling `conda-lock -p win-64 environment.yml` on a Linux box fails with:

```
The following packages are not available from current channels:

  - m2w64-gcc-libs

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I believe this is because `defaults` only includes the `msys2` package on Windows, so running the solver on Linux removes this channel and causes this failure.

**Comment by alanhdu** [comment]
One cheap (if hacky) way to do this would be to inject the `msys2` channel when calling `conda` at. I'd be happy to send the short PR if that's an acceptable solution.

https://github.com/mariusvniekerk/conda-lock/blob/182d64d9c2a802a3761c6f32763b6d4bf12770ef/conda_lock/conda_lock.py#L114-L115

**Comment by alanhdu** [comment]
(as a side-note, thanks so much for building this. This is something I've wanted for literally years now, and I'm *so* happy that it exists).

**Comment by mariusvniekerk** [comment]
Yeah that would be greatly appreciated

**Comment by ocefpaf** [comment]
> One cheap (if hacky) way to do this would be to inject the msys2 channel when calling conda at. I'd be happy to send the short PR if that's an acceptable solution.

Agreed. It makes sense to inject all the parts that mean `main` (aka `defaults`) on Window when calling it from a Linux box. Ideally we should upstream that and/or look into conda's docs to see if that doesn't exist already, but ` -p win-64` should just work.
